# coding: utf-8

"""
    Paheko API

    Documentation Swagger pour l'API de Paheko  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.transaction_idtransaction_body import TransactionIDTRANSACTIONBody  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionIDTRANSACTIONBody(unittest.TestCase):
    """TransactionIDTRANSACTIONBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionIDTRANSACTIONBody(self):
        """Test TransactionIDTRANSACTIONBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.transaction_idtransaction_body.TransactionIDTRANSACTIONBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
