# coding: utf-8

"""
    Paheko API

    Documentation Swagger pour l'API de Paheko  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/paheko-api/paheko-codegen.git
"""

from __future__ import absolute_import

import unittest

import paheko_client
from paheko_client.models.idtransaction_subscriptions_body import IDTRANSACTIONSubscriptionsBody  # noqa: E501
from paheko_client.rest import ApiException


class TestIDTRANSACTIONSubscriptionsBody(unittest.TestCase):
    """IDTRANSACTIONSubscriptionsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIDTRANSACTIONSubscriptionsBody(self):
        """Test IDTRANSACTIONSubscriptionsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = paheko_client.models.idtransaction_subscriptions_body.IDTRANSACTIONSubscriptionsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
