# coding: utf-8

"""
    Paheko API

    Documentation Swagger pour l'API de Paheko  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.idtransaction_transactions_body import IDTRANSACTIONTransactionsBody  # noqa: E501
from swagger_client.rest import ApiException


class TestIDTRANSACTIONTransactionsBody(unittest.TestCase):
    """IDTRANSACTIONTransactionsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIDTRANSACTIONTransactionsBody(self):
        """Test IDTRANSACTIONTransactionsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.idtransaction_transactions_body.IDTRANSACTIONTransactionsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
