# coding: utf-8

"""
    Paheko API

    Documentation Swagger pour l'API de Paheko  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/paheko-api/paheko-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserNewBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      paheko_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    paheko_types = {
        'nom': 'str',
        'prenom': 'str',
        'email': 'str',
        'id_category': 'int',
        'password': 'str'
    }

    attribute_map = {
        'nom': 'nom',
        'prenom': 'prenom',
        'email': 'email',
        'id_category': 'id_category',
        'password': 'password'
    }

    def __init__(self, nom=None, prenom=None, email=None, id_category=None, password=None):  # noqa: E501
        """UserNewBody - a model defined in Swagger"""  # noqa: E501
        self._nom = None
        self._prenom = None
        self._email = None
        self._id_category = None
        self._password = None
        self.discriminator = None
        self.nom = nom
        self.prenom = prenom
        self.email = email
        self.id_category = id_category
        self.password = password

    @property
    def nom(self):
        """Gets the nom of this UserNewBody.  # noqa: E501


        :return: The nom of this UserNewBody.  # noqa: E501
        :rtype: str
        """
        return self._nom

    @nom.setter
    def nom(self, nom):
        """Sets the nom of this UserNewBody.


        :param nom: The nom of this UserNewBody.  # noqa: E501
        :type: str
        """
        if nom is None:
            raise ValueError("Invalid value for `nom`, must not be `None`")  # noqa: E501

        self._nom = nom

    @property
    def prenom(self):
        """Gets the prenom of this UserNewBody.  # noqa: E501


        :return: The prenom of this UserNewBody.  # noqa: E501
        :rtype: str
        """
        return self._prenom

    @prenom.setter
    def prenom(self, prenom):
        """Sets the prenom of this UserNewBody.


        :param prenom: The prenom of this UserNewBody.  # noqa: E501
        :type: str
        """
        if prenom is None:
            raise ValueError("Invalid value for `prenom`, must not be `None`")  # noqa: E501

        self._prenom = prenom

    @property
    def email(self):
        """Gets the email of this UserNewBody.  # noqa: E501


        :return: The email of this UserNewBody.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserNewBody.


        :param email: The email of this UserNewBody.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def id_category(self):
        """Gets the id_category of this UserNewBody.  # noqa: E501


        :return: The id_category of this UserNewBody.  # noqa: E501
        :rtype: int
        """
        return self._id_category

    @id_category.setter
    def id_category(self, id_category):
        """Sets the id_category of this UserNewBody.


        :param id_category: The id_category of this UserNewBody.  # noqa: E501
        :type: int
        """
        if id_category is None:
            raise ValueError("Invalid value for `id_category`, must not be `None`")  # noqa: E501

        self._id_category = id_category

    @property
    def password(self):
        """Gets the password of this UserNewBody.  # noqa: E501


        :return: The password of this UserNewBody.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this UserNewBody.


        :param password: The password of this UserNewBody.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.paheko_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserNewBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserNewBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
